version: "3"

services:
  postgres:
    container_name: "${PROJECT_PREFIX}-postgres"
    build:
      context: ./docker/postgres
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
